- Childrens-Social-Care-CPD/Program.cs
- Childrens-Social-Care-CPD/Views/PartialViews/SideNav.cshtml
- Childrens-Social-Care-CPD/Views/Shared/_Layout.cshtml
Added settings to allow webserver to catch and show error details on App Startup.
> Feature enable startup exception capture

- Childrens-Social-Care-CPD/Childrens-Social-Care-CPD.csproj
- Childrens-Social-Care-CPD/Program.cs
Added App Insights Telemetry support - Hard coded connection string to AppInsights dev environment.
> Added AppInsights - Telemetry support

- Terraform/application.tf
@dolphincrs or @nnagepat to check if this is an acceptable name for the environment var:
CPD_INSTRUMENTATION_KEY
> Add environment variable for application insights

- Terraform/appgw.tf
* Update OWASP verison to 3.2
* Use different selector for WAF on Load-Test and Prod Environments
> Update rule set and WAF Config selection

- Childrens-Social-Care-CPD/Views/Shared/_Layout.cshtml
Reverts DFE-Digital/childrens-social-care-cpd#39
> Revert "Updated code to G-Tag to respond to all environments"

- .github/workflows/terraform-destroy.yml
- .github/workflows/terraform-plan.yml
- .github/workflows/terraform.yml
Modify Terraform GitHub action to add following vars from secrets:
```
TF_VAR_cpd_space_id: ${{secrets.TF_VAR_CPD_SPACE_ID}}
TF_VAR_cpd_preview_key: ${{secrets.TF_VAR_CPD_PREVIEW_KEY}}
TF_VAR_cpd_delivery_key: ${{secrets.TF_VAR_CPD_DELIVERY_KEY}}
```
> Update GitHub actions keys

- .github/workflows/restore-contentful.yml
Use Prod environment which has deployment approval Use Prod space instead of Dev
> Set restore action to Prod

- .github/workflows/backup-contentful.yml
Use a secret for the email address used to perform the contentful backup.
> Use secret for email address

- LoadTest/locustfile.py
Tested against dev and seemed to work ok
> Updated the load test with new page urls for the new content model

- Childrens-Social-Care-CPD/Contentful/Models/DetailedPathway.cs
- Childrens-Social-Care-CPD/Views/Shared/_DetailedPathway.cshtml
Simple change to support the different look on the ASYE page
> Modify the detailed pathway to allow the ASYE page to work

- .github/workflows/load-testing.yml
> feat: Modified Load Test

- .github/workflows/load-testing.yml
Add pip3 install charset_normalizer
> feat: Add pip3 install charset_normalizer

- browser-tests/content-regression-tests/tests/explore-area-of-practice/assessment-and-intake.spec.ts
- browser-tests/content-regression-tests/tests/explore-area-of-practice/courts.spec.ts
- browser-tests/content-regression-tests/tests/explore-area-of-practice/youth-justice.spec.ts
> tests: Added Addition UI Tests

- Terraform/ai-search.tf
- Terraform/private-endpoint.tf
- Terraform/variables.tf
Create new object for AI Search Service
Create new variable for AI Search Service Name
> Add Terraform for AI Search Service

- .github/workflows/load-testing.yml
- .github/workflows/terraform-destroy.yml
- .github/workflows/terraform-plan.yml
- .github/workflows/terraform.yml
Add variables for AI Search Function App which will be deployed (or destroyed) by Terraform in the GitHub Actions.
> Add TF Vars for new search function into GitHub Actions

- .github/workflows/load-testing.yml
- .github/workflows/terraform-destroy.yml
- .github/workflows/terraform-plan.yml
- .github/workflows/terraform.yml
- README.md
- Terraform/README.md
- Terraform/application.tf
- Terraform/variables.tf
Also update actions and use index name and endpoint.
> Add Client Search API Key in Terraform

- .github/workflows/load-testing.yml
- .github/workflows/terraform-destroy.yml
- .github/workflows/terraform-plan.yml
- .github/workflows/terraform.yml
- Terraform/README.md
- Terraform/grafana.tf
- Terraform/variables.tf
* currently only loads the cost plugin but secret can be amended to add others
> Add plugins to load into Grafana at runtime

- Childrens-Social-Care-CPD/Views/Shared/_ErrorLayout.cshtml
- Childrens-Social-Care-CPD/Views/Shared/_Header.cshtml
- browser-tests/content-regression-tests/tests/career-stages/develop-social-work-practice.spec.ts
- browser-tests/content-regression-tests/tests/career-stages/experienced-practitioners.spec.ts
Change Career stages Navigation url
> feat: Change Career stages Navigation url

- browser-tests/content-regression-tests/tests/career-stages/asye.spec.ts
- browser-tests/content-regression-tests/tests/career-stages/leaders.spec.ts
- browser-tests/content-regression-tests/tests/career-stages/managers.spec.ts
- browser-tests/content-regression-tests/tests/career-stages/pathway-1-practice-supervisors.spec.ts
- browser-tests/content-regression-tests/tests/career-stages/pathway-2-middle-managers.spec.ts
- browser-tests/content-regression-tests/tests/career-stages/pathway-3-heads-of-service.spec.ts
- browser-tests/content-regression-tests/tests/career-stages/pathway-4-practice-leaders.spec.ts
- browser-tests/content-regression-tests/tests/career-stages/practitioners.spec.ts
- browser-tests/content-regression-tests/tests/career-stages/senior-managers.spec.ts
- browser-tests/content-regression-tests/tests/career-stages/upon-aspirant-directors-programme.spec.ts
- browser-tests/content-regression-tests/tests/career-stages/upon-new-directors-programme.spec.ts
- browser-tests/content-regression-tests/tests/explore-area-of-practice/assessment-and-intake.spec.ts
- browser-tests/content-regression-tests/tests/explore-area-of-practice/child-protection-and-family-safeguarding.spec.ts
- browser-tests/content-regression-tests/tests/explore-area-of-practice/courts.spec.ts
- browser-tests/content-regression-tests/tests/explore-area-of-practice/youth-justice.spec.ts
- browser-tests/content-regression-tests/tests/footer.spec.ts
- browser-tests/content-regression-tests/tests/header.spec.ts
- browser-tests/content-regression-tests/tests/homepage.spec.ts
> Updated Regression UI Tests

- Childrens-Social-Care-CPD/WebApplicationBuilderExtensions.cs
This reverts commit 42a0ac220c1e0700b556d2ae5b916611f2399cd0.
> fix: Revert back to ManagedAzureCredential for data protection

- Childrens-Social-Care-CPD/Program.cs
BREAKING CHANGE: Update to .Net 8
> feat: Trigger major release

- Terraform/README.md
- Terraform/private-endpoint.tf
Add a new DNS Zone for the Storage Account Private Link 
* privatelink.blob.core.windows.net
> Fix DNS Zone for Storage Account Private Link

- .github/workflows/docker-publish.yml
Set version of installer back to v3.4.0 and added command line switch to suppress need for user input when signing
> ci: Mattb/set cosign installer version v3.4.0

- .github/workflows/docker-publish.yml
- README.md
Put whitespace into the README to trigger a build
> fix: Mattb/set cosign installer version v3.2.0

- Contentful-Schema/README.md
Simply a whitespace change in a README to trigger a release build
> feat: trigger release build

- Childrens-Social-Care-CPD/package-lock.json
- Contentful-Schema/package-lock.json
Bumps the npm_and_yarn group with 3 updates in the /Childrens-Social-Care-CPD directory: [serve-static](https://github.com/expressjs/serve-static), [webpack](https://github.com/webpack/webpack) and [ws](https://github.com/websockets/ws).
Bumps the npm_and_yarn group with 3 updates in the /Contentful-Schema directory: [braces](https://github.com/micromatch/braces), [micromatch](https://github.com/micromatch/micromatch) and [axios](https://github.com/axios/axios).
Updates `serve-static` from 1.15.0 to 1.16.2
- [Release notes](https://github.com/expressjs/serve-static/releases)
- [Changelog](https://github.com/expressjs/serve-static/blob/v1.16.2/HISTORY.md)
- [Commits](https://github.com/expressjs/serve-static/compare/v1.15.0...v1.16.2)
Updates `webpack` from 4.46.0 to 4.47.0
- [Release …
> Bump the npm_and_yarn group across 2 directories with 6 updates

- Childrens-Social-Care-CPD/wwwroot/sitemap.xml
> Sitemap change Monday 17-02-2025 10:04:11

- Childrens-Social-Care-CPD/wwwroot/sitemap.xml
> Sitemap change Tuesday 18-02-2025 12:28:41

- docs/architecture/decisions/003-static-code-analysis.md
ADR for replacing SonarCloud with GHAS and Trivy
> SFSW-2873 Add ADR 003 for sonarcloud replacements

- Childrens-Social-Care-CPD/Views/Shared/_ErrorLayout.cshtml
- Childrens-Social-Care-CPD/Views/Shared/_Footer.cshtml
- browser-tests/content-regression-tests/tests/footer.spec.ts
- browser-tests/dev-integration-tests/tests/footer.spec.ts
Change word in footer: Alter from 'Site Map' to 'Sitemap' as requested by Claire on Slack.
> sitemap word amended

- .github/workflows/docker-contentful-space-export.yml
- .github/workflows/docker-contentful-space-import.yml
- Childrens-Social-Care-CPD/Dockerfile
- Contentful-Backup/Dockerfile
Adds nonroot user for DS002 Trivy alert, disables Contentful triggers and adds tagged Node version for DS001 Trivy alert.
> Add nonroot

- Childrens-Social-Care-CPD/wwwroot/sitemap.xml
> Sitemap change Friday 28-02-2025 15:31:03

- Childrens-Social-Care-CPD/wwwroot/sitemap.xml
> Sitemap change Tuesday 22-04-2025 08:56:47

- Childrens-Social-Care-CPD/wwwroot/sitemap.xml
> Sitemap change Monday 09-06-2025 09:26:06
